// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"build-microservice-with-go/products/models"
)

// StoreProductReader is a Reader for the StoreProduct structure.
type StoreProductReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StoreProductReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStoreProductOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewStoreProductOK creates a StoreProductOK with default headers values
func NewStoreProductOK() *StoreProductOK {
	return &StoreProductOK{}
}

/*StoreProductOK handles this case with default header values.

Data structure representing a single product
*/
type StoreProductOK struct {
	Payload *models.Product
}

func (o *StoreProductOK) Error() string {
	return fmt.Sprintf("[POST /products][%d] storeProductOK  %+v", 200, o.Payload)
}

func (o *StoreProductOK) GetPayload() *models.Product {
	return o.Payload
}

func (o *StoreProductOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Product)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
